### PR TITLE
fix(router/api/profile): fetching git repos don't need OAuth anymore

### PR DESCRIPTION
**Pull request by brandonwie**

### CODE REVIEW

**Comment by bushblade** [comment]
Hi @brandonwie 
Please have a read of [this section of the README](https://github.com/bradtraversy/devconnector_2.0#changes-to-github-api-authentication)
We use an access token in the request headers to authenticate. You need to authenticate otherwise you will get rate limited on the number of requests you can make, which I think will be a max of 30 per hour IIRC.

**Comment by brandonwie** [comment]
Thanks Will for the reply.
I have tried multiple times with my OAuth token, but it has a problem with
Rate Limit and I didn't make 5k calls per day.
Is there any way around with this?
Thanks.

**Comment by bushblade** [comment]
Do you mean an access token?
If you are using an access token in the request headers as per the current repository code, if you push code to your remote Github repository that contains your access token (config/default.json or config/production.json) then Github will revoke your token and the request will fail.
Perhaps that is what is happening for you?

**Comment by brandonwie** [comment]
I followed the instruction on the README.md, but somehow it didn't work. I
will try by myself. Truly thanks for your time.

**Comment by bushblade** [comment]
Check your Github repo for the project, does it contain a confing/default.json or config/production.json ?
If so and your access token is stored in there, then your token will have been revoked.
Also log out the response from the Github API in your route controller, it will tell you what the issue is there.

**Comment by brandonwie** [comment]
I read more carefully all the instructions and it works perfectly. Thank
you so much for your time. Idk if you’re managing Brad’s Nextjs course as
well, but if you do, see you there 🙂

**Comment by bushblade** [comment]
No worries, glad to hear it. Yeah you may see me in that course too.

**Pull request closed without merging**
