### PR TITLE
Store user destination on page load

### PR DESCRIPTION
**Pull request by corey01**
On page load, the users destination is stored, after the 'isAuthenticated' check is complete, if the destination was not '/dashboard', the user will be forwarded to their previous location.

### CODE REVIEW

**Comment by bushblade** [comment]
Hi @corey01 thanks for taking the time to look into this.
I pulled your changes into a test branch and gave them a go, it does work yes.
I'm not sure I feel it is the ideal solution though as you 'bounce' around in the routes a couple of times before it resolves.
It has made me have a look and see what we can do here though.
I think perhaps the simplest solution is to change our private route to..
```js
const PrivateRoute = ({
  component: Component,
  auth: { isAuthenticated, loading },
  ...rest
}) => (
  <Route
    {...rest}
    render={props =>
      loading ? (
        <Spinner />
      ) : isAuthenticated ? (
        <Component {...props} />
      ) : (
        <Redirect to="/login" />
      )
    }
  />
);
```
And add in a case for AUTH_ERROR to set loading back to false so if we refresh and a user is not authenticated the spinner doesn't spin forever and we get re routed accordingly.
```js
    case AUTH_ERROR:
    case LOGOUT:
      return {
        ...state,
        token: null,
        isAuthenticated: false,
        loading: false,
        user: null
      };
```
I may merge these changes myself, but would appreciate you having a look to see if you agree.
Currently they are in a [refreshroutes branch in my repo here](https://github.com/bushblade/devconnector_2.0/tree/refreshroutes)

**Comment by corey01** [comment]
Hi Bushblade,

Thanks for the response. I do think your solution is much cleaner, however I can't seem to get it to work here. Refreshing still sends the user back to the the dashboard page.

I think this is because the redux store is initially just set as 'token: null' within the store.js file..

changing this to the following in your code:

`// prevent auth error on first run of subscription
const initialState = { 
  auth: {
    token: null,
    isAuthenticated: null,
    loading: true,
    user: null
  }
};`

within client/src/store.js seems to solve it (just mirroring the default auth state with token set to null)

What do you think of adding this into your branch?

**Comment by bushblade** [comment]
Hi @corey01 yes that makes sense and would be a great solution. I'll add that in.
Thanks for your feedback.

**Comment by corey01** [comment]
I've closed my pull request as I much prefer your solution.

Thanks again @bushblade

**Pull request closed without merging**
