### PR TITLE
Update auth.js

### PR DESCRIPTION
**Pull request by qkrrbtjd90**
no reducer for LOGIN_FAIL and REGISTER_FAIL

### CODE REVIEW

**Comment by bushblade** [comment]
Hi @qkrrbtjd90 
Can you explain why this is needed?

**Comment by qkrrbtjd90** [comment]
@bushblade I don't know why, but you got rid of LOGIN_FAIL and REGISTER_FAIL in auth reducer. I guess you can add those back in auth reducer to make it work?

**Comment by kirasiris** [comment]
@qkrrbtjd90 have you been able to reproduce the error with the current version of this repository? Or is it just in your application?

**Comment by qkrrbtjd90** [comment]
@kirasiris I have been doing the MERN course online and noticed that this repository is different then what is on the video. So, I have been comparing the two codes and notice that this one does not have LOGIN_FAIL and REGISTER_FAIL. 

If you look at auth.js in actions it is dispatching LOGIN_FAIL and REGISER_FAIL, but if you look at auth.js  in reducers it does not handle those two cases at all. So, if I am correct, you will have to either

1. dispatch AUTH_ERROR (which I submitted) which doesn't seem like the best solution, but sill works 
2. add LOGIN_FAIL and REGISTER_FAIL under auth.js in reducers top handle these cases.

**Comment by bushblade** [comment]
There is no state change needed on a LOGIN_FAIL or a REGISTER_FAIL though. In either case it will be after initial loading of the app and returning default state would be the desired state update. The return of default state in the reducer is the case for LOGIN_FAIL or REGISTER_FAIL. Dispatching those types from the auth actions is necessary for accurate feedback in redux dev tools in development, but we only need to return the default initial state.

**Comment by qkrrbtjd90** [comment]
Okay awesome. Thank you for the explanation. For someone just learning MERN, this wasn't very clear because Brad did mention that you want to handle the cases in reducer when you dispatch an action. Appreciate your explanation.

**Comment by bushblade** [comment]
No problem I'll close the issue.

**Pull request closed without merging**
