### PR TITLE
Update ProfileTop.js have a cleaner JS code.

### PR DESCRIPTION
**Pull request by codeghoul**
I figured that the keys we used in our social links go well with icons too so decided to go with Object.entries approach.

### CODE REVIEW

**Comment by bushblade** [comment]
Hi @codeghoul 
Yeah that is cleaner, you could further clean it by destructuring...
```js
 {social &&
          Object.entries(social).map(([key, value]) => {
            return (
              <a
                key={key}
                href={value}
                target='_blank'
                rel='noopener noreferrer'
              >
                <i className={`fab fa-${key} fa-2x`}></i>
              </a>
            );
          })}
```
Or you could probably just use the url as the key...
```js
 {social &&
          Object.values(social).map((link) => {
            return (
              <a
                key={link}
                href={link}
                target='_blank'
                rel='noopener noreferrer'
              >
                <i className={`fab fa-${key} fa-2x`}></i>
              </a>
            );
          })}
```
I've not tested either, but should be ok.

**Comment by bushblade** [comment]
Or use and implicit return too...
```js
 {social &&
          Object.values(social).map((link) => (
              <a
                key={link}
                href={link}
                target='_blank'
                rel='noopener noreferrer'
              >
                <i className={`fab fa-${key} fa-2x`}></i>
              </a>
            )
          )}
```

**Comment by codeghoul** [comment]
Hey! Thanks for the suggestions I've updated the request and learned something too.

**Comment by bushblade** [comment]
No worries. I don't see the change though.

**Comment by codeghoul** [comment]
Can you check again, I have added a new commit and I can see the changes in the file changed tab.

**Comment by bushblade** [comment]
Hi again @codeghoul 
Yes thanks that's up to date now.

**Pull request merged**
