### PR TITLE
Fix Delete Comment Route

### PR DESCRIPTION
**Pull request by cybergeek7**
Fixed Delete Comment Route

### CODE REVIEW

**Comment by bushblade** [comment]
Hi @cybergeek7 
Can you explain what this fixes please?

**Comment by cybergeek7** [comment]
Hi @bushblade,

First of all changed the id to **_id**, to match the MongoDB document.
second thing, casted the returned _id  to a string to match with the params ID's, which are strings.

**Comment by bushblade** [comment]
I don't think there should be any issue with the former as Mongoose provides a `id` getter on the Model/document so `comment.id` is the same as `comment _id.toString()`
Did you get any errors here before ?

**Comment by cybergeek7** [comment]
Looks like now postman is working even with the original code!
Oh I didn't know that "Mongoose provides a id getter on the Model/document". Thank you for the information, Will!
I'm actually still learning and you're awesome!

**Comment by bushblade** [comment]
No worries, thanks for the kind words.

**Pull request closed without merging**
